apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: teste
  annotations:
    github.com/project-slug: luanabittencourt/teste
spec:
  type: other
  lifecycle: unknown
  owner: arcotech
